[project]
name = "livekit-voice-agent"
version = "0.1.0"
requires-python = ">=3.11,<3.14"
dependencies = [
    "livekit-agents[openai,google]~=1.2",
    "livekit-plugins-noise-cancellation~=0.2",
    "python-dotenv>=1.2.1",
]
